// Copyright (c) 2019-2025 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

namespace ReactiveUI.Extensions.Async;

/// <summary>
/// Provides factory methods for creating observable sequences that are generated by invoking a specified function each
/// time a new observer subscribes.
/// </summary>
/// <remarks>The methods in this class enable deferred creation of asynchronous observable sequences. Each
/// subscription triggers a new invocation of the provided factory function, ensuring that each observer receives a
/// fresh sequence. This is useful for scenarios where the observable's behavior or state should be determined at the
/// time of subscription rather than at the time of declaration.</remarks>
public static partial class ObservableAsync
{
    /// <summary>
    /// Creates a new observable sequence for each subscription by invoking the specified asynchronous factory function.
    /// </summary>
    /// <remarks>Use this method to defer the creation of the observable sequence until an observer
    /// subscribes. This is useful when the observable sequence depends on per-subscription state or resources, or when
    /// you want to ensure a fresh sequence for each subscriber.</remarks>
    /// <typeparam name="T">The type of the elements produced by the observable sequence.</typeparam>
    /// <param name="factory">A function that receives a cancellation token and returns a task that produces an observable sequence to
    /// subscribe to.</param>
    /// <returns>An observable sequence that, upon each subscription, invokes the factory function to obtain the actual
    /// observable sequence to subscribe to.</returns>
    public static ObservableAsync<T> Defer<T>(Func<CancellationToken, ValueTask<ObservableAsync<T>>> factory) =>
        Create<T>(async (observer, token) =>
        {
            var observable = await factory(token);
            return await observable.SubscribeAsync(observer.Wrap(), token);
        });

    /// <summary>
    /// Returns an observable sequence that is created by invoking the specified factory function each time a new
    /// observer subscribes.
    /// </summary>
    /// <remarks>Use this method to defer the creation of the observable sequence until an observer
    /// subscribes, ensuring that each subscription receives a fresh instance. This is useful when the observable
    /// sequence has side effects or depends on external state at the time of subscription.</remarks>
    /// <typeparam name="T">The type of the elements produced by the observable sequence.</typeparam>
    /// <param name="factory">A function that returns a new instance of an observable sequence to be subscribed to for each observer.</param>
    /// <returns>An observable sequence whose observers trigger the invocation of the factory function upon subscription.</returns>
    public static ObservableAsync<T> Defer<T>(Func<ObservableAsync<T>> factory) =>
        Create<T>(async (observer, token) =>
        {
            var observable = factory();
            return await observable.SubscribeAsync(observer.Wrap(), token);
        });
}
